# Generated by Django 4.0.3 on 2023-06-14 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('healthapp', '0005_alter_consultationform_consult_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Update your Name', max_length=20, null=True)),
                ('address', models.CharField(default='Update your Address', max_length=100, null=True)),
                ('bio', models.CharField(default='Update your bio', max_length=200, null=True)),
                ('email', models.CharField(default='Update your Email', max_length=20, null=True)),
                ('phone', models.CharField(default='Update your phone no', max_length=20, null=True)),
                ('profile_img', models.ImageField(blank=True, default='media/default-avatar.png', null=True, upload_to='media')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
